[build]
  publish = "dist"
  command = "npm run build"

[build.processing.html]
  pretty_urls = false

# Environment variables
[build.environment]
  NETLIFY_USE_PNPM = "false"
  GATSBY_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

# Handle admin routes - serve index.html for /admin
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = false

# Handle all other admin routes
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = false

# Handle Netlify Identity
# Note: These redirects are handled automatically by Netlify, no need to specify them

# Serve config.yml from static/admin
[[redirects]]
  from = "/admin/config.yml"
  to = "/admin/config.yml"
  status = 200
  force = true

# Serve node_modules in development
[[redirects]]
  from = "/node_modules/*"
  to = "/node_modules/:splat"
  status = 200
  force = true
  
# Make sure node_modules is accessible in development
[[headers]]
  for = "/node_modules/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

# CSP for admin routes
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for admin
# Admin page headers - minimal for development
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; img-src * data:; font-src * data:; connect-src *;"

# Test page - minimal headers for debugging
[[headers]]
  for = "/admin-test.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    
# Make sure the test page is served with the correct MIME type
[[redirects]]
  from = "/admin-test.html"
  to = "/admin-test.html"
  status = 200
  force = true

# Global headers - exclude test page
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
    Feature-Policy = "camera 'none'; microphone 'none'; geolocation 'none';"

# Explicitly exclude test page from global headers
[[headers]]
  for = "/admin-test.html"
  [headers.values]
    X-Content-Type-Options = ""
    X-Frame-Options = ""
    X-XSS-Protection = ""
    Referrer-Policy = ""
    Content-Security-Policy = ""
    Feature-Policy = ""

# Cache control for static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow Netlify Identity to work
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
