// This file is auto-generated by Tina
import { getSsrClient } from "tinacms/next/ssr";
import { createClient } from "../tina/__generated__/client";

// This is the client that will be used in the browser
const client = createClient({
  url: 'http://localhost:4001/graphql',
  queries: (client) => ({
    // Add your queries here
  }),
});

export default client;
