# Backend configuration (Git Gateway for production, local for development)
backend:
  name: git-gateway
  branch: main
  
# Local development backend (uncomment for local development)
local_backend: true

# Media and public folders
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Site settings
site_url: http://localhost:4321  # Update this to match your local development URL
display_url: http://localhost:4321

# Collections configuration
collections:
  # Blog Posts
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          required: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { 
          label: "Draft", 
          name: "draft", 
          widget: "boolean", 
          required: false, 
          default: false 
        }
